# coding: utf-8

"""
    Apache Polaris and Apache Iceberg REST Catalog API

    Defines the specification for the Polaris Catalog API, which encompasses both the Iceberg REST Catalog API and Polaris-native API.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from polaris.catalog.models.catalog_identifier import CatalogIdentifier

class TestCatalogIdentifier(unittest.TestCase):
    """CatalogIdentifier unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CatalogIdentifier:
        """Test CatalogIdentifier
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CatalogIdentifier`
        """
        model = CatalogIdentifier()
        if include_optional:
            return CatalogIdentifier(
                catalog = ''
            )
        else:
            return CatalogIdentifier(
                catalog = '',
        )
        """

    def testCatalogIdentifier(self):
        """Test CatalogIdentifier"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
