# coding: utf-8

"""
    Apache Polaris and Apache Iceberg REST Catalog API

    Defines the specification for the Polaris Catalog API, which encompasses both the Iceberg REST Catalog API and Polaris-native API.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from polaris.catalog.models.load_credentials_response import LoadCredentialsResponse

class TestLoadCredentialsResponse(unittest.TestCase):
    """LoadCredentialsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> LoadCredentialsResponse:
        """Test LoadCredentialsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `LoadCredentialsResponse`
        """
        model = LoadCredentialsResponse()
        if include_optional:
            return LoadCredentialsResponse(
                storage_credentials = [
                    polaris.catalog.models.storage_credential.StorageCredential(
                        prefix = '', 
                        config = {
                            'key' : ''
                            }, )
                    ]
            )
        else:
            return LoadCredentialsResponse(
                storage_credentials = [
                    polaris.catalog.models.storage_credential.StorageCredential(
                        prefix = '', 
                        config = {
                            'key' : ''
                            }, )
                    ],
        )
        """

    def testLoadCredentialsResponse(self):
        """Test LoadCredentialsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
