# coding: utf-8

"""
    Apache Polaris and Apache Iceberg REST Catalog API

    Defines the specification for the Polaris Catalog API, which encompasses both the Iceberg REST Catalog API and Polaris-native API.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from polaris.catalog.models.get_applicable_policies_response import GetApplicablePoliciesResponse

class TestGetApplicablePoliciesResponse(unittest.TestCase):
    """GetApplicablePoliciesResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetApplicablePoliciesResponse:
        """Test GetApplicablePoliciesResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetApplicablePoliciesResponse`
        """
        model = GetApplicablePoliciesResponse()
        if include_optional:
            return GetApplicablePoliciesResponse(
                next_page_token = '',
                policies = [
                    polaris.catalog.models.policy.Policy(
                        policy_type = '', 
                        name = 'compaction', 
                        description = '', 
                        content = '', 
                        version = 56, 
                        created_at_ms = 56, 
                        updated_at_ms = 56, )
                    ]
            )
        else:
            return GetApplicablePoliciesResponse(
                policies = [
                    polaris.catalog.models.policy.Policy(
                        policy_type = '', 
                        name = 'compaction', 
                        description = '', 
                        content = '', 
                        version = 56, 
                        created_at_ms = 56, 
                        updated_at_ms = 56, )
                    ],
        )
        """

    def testGetApplicablePoliciesResponse(self):
        """Test GetApplicablePoliciesResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
