# coding: utf-8

"""
    Apache Polaris and Apache Iceberg REST Catalog API

    Defines the specification for the Polaris Catalog API, which encompasses both the Iceberg REST Catalog API and Polaris-native API.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from polaris.catalog.models.iceberg_error_response1 import IcebergErrorResponse1

class TestIcebergErrorResponse1(unittest.TestCase):
    """IcebergErrorResponse1 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IcebergErrorResponse1:
        """Test IcebergErrorResponse1
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IcebergErrorResponse1`
        """
        model = IcebergErrorResponse1()
        if include_optional:
            return IcebergErrorResponse1(
                error = polaris.catalog.models.error_model.ErrorModel(
                    message = '', 
                    type = 'NoSuchNamespaceException', 
                    code = 404, 
                    stack = [
                        ''
                        ], )
            )
        else:
            return IcebergErrorResponse1(
                error = polaris.catalog.models.error_model.ErrorModel(
                    message = '', 
                    type = 'NoSuchNamespaceException', 
                    code = 404, 
                    stack = [
                        ''
                        ], ),
        )
        """

    def testIcebergErrorResponse1(self):
        """Test IcebergErrorResponse1"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
