# coding: utf-8

"""
    Apache Polaris and Apache Iceberg REST Catalog API

    Defines the specification for the Polaris Catalog API, which encompasses both the Iceberg REST Catalog API and Polaris-native API.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class NotificationType(str, Enum):
    """
    NotificationType
    """

    """
    allowed enum values
    """
    UNKNOWN = 'UNKNOWN'
    CREATE = 'CREATE'
    UPDATE = 'UPDATE'
    DROP = 'DROP'
    VALIDATE = 'VALIDATE'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of NotificationType from a JSON string"""
        return cls(json.loads(json_str))


